/**
 * Regenerates THIRD-PARTY-NOTICES.md from what the bundle actually contains.
 *
 * The list is read out of the build's sourcemap rather than written by hand:
 * a dependency upgrade can pull in new transitive packages, and a hand-kept
 * list goes stale silently — which is exactly the kind of omission the MIT
 * notice requirement is about.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const extension = join(here, '..');
const repo = join(extension, '..');

const mapFile = join(extension, 'dist/extension.js.map');
if (!existsSync(mapFile)) {
  console.error('notices: build the extension first (npm run build)');
  process.exit(1);
}

const map = JSON.parse(readFileSync(mapFile, 'utf8'));
const names = new Set();
for (const source of map.sources) {
  const at = source.lastIndexOf('node_modules/');
  if (at < 0) continue;
  const rest = source.slice(at + 'node_modules/'.length).split('/');
  names.add(rest[0].startsWith('@') ? `${rest[0]}/${rest[1]}` : rest[0]);
}

const LICENSE_FILES = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license', 'LICENCE'];

const HEADER = [
  '# Third-party notices',
  '',
  'This file is generated by `scripts/notices.mjs` from the build output — do not edit it by hand.',
  '',
];

if (names.size === 0) {
  writeFileSync(
    join(extension, 'THIRD-PARTY-NOTICES.md'),
    [
      ...HEADER,
      'The extension bundles no third-party code: the library it ships has no',
      'dependencies of its own, so there are no notices to reproduce.',
      '',
    ].join('\n'),
  );
  console.log('notices: nothing third-party is bundled');
  process.exit(0);
}

const parts = [
  ...HEADER,
  'The published extension bundles its dependencies into `dist/extension.js`.',
  'Their licences are reproduced below, as those licences require.',
  '',
];

for (const name of [...names].sort()) {
  // Dependencies are hoisted to the repo root, since the extension resolves
  // the core library and its deps from there.
  const dir = [join(repo, 'node_modules', name), join(extension, 'node_modules', name)].find((d) =>
    existsSync(join(d, 'package.json')),
  );
  if (!dir) {
    console.error(`notices: cannot locate ${name} — is it installed?`);
    process.exit(1);
  }

  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  const licenseFile = LICENSE_FILES.find((f) => existsSync(join(dir, f)));
  const text = licenseFile
    ? readFileSync(join(dir, licenseFile), 'utf8').trim()
    : `${pkg.license} — the package ships no licence file; see ${pkg.homepage ?? pkg.repository?.url ?? 'its repository'}`;

  parts.push(
    `## ${pkg.name} ${pkg.version}`,
    '',
    [pkg.license, pkg.homepage].filter(Boolean).join(' — '),
    '',
    '```',
    text,
    '```',
    '',
  );
}

writeFileSync(join(extension, 'THIRD-PARTY-NOTICES.md'), parts.join('\n'));
console.log(`notices: ${names.size} bundled packages documented — ${[...names].sort().join(', ')}`);
