// Inlines the viewer sources into a TypeScript module so the HTML renderer can
// emit one self-contained file with no runtime file reads.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const css = await readFile(join(root, 'src/viewer/viewer.css'), 'utf8');
const js = await readFile(join(root, 'src/viewer/viewer.js'), 'utf8');

const out = `/* eslint-disable */
// Generated by scripts/build-assets.mjs — edit src/viewer/* instead.
export const VIEWER_CSS = ${JSON.stringify(css)};
export const VIEWER_JS = ${JSON.stringify(js)};
`;

await writeFile(join(root, 'src/render/assets.generated.ts'), out);
console.log(`assets: ${css.length} B css + ${js.length} B js inlined`);
